# Generated by Django 6.0.2 on 2026-02-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_blocked',
        ),
    ]
