# Generated by Django 6.0.2 on 2026-02-12 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='co_instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_lecturer', to=settings.AUTH_USER_MODEL),
        ),
    ]
