# Generated by Django 4.2.25 on 2026-02-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_co_instuctors_course_co_instructors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='TEMP001', max_length=20, unique=True),
        ),
    ]
