# Generated by Django 6.0.2 on 2026-02-15 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='completed_users',
            field=models.ManyToManyField(blank=True, related_name='completed_contents', to=settings.AUTH_USER_MODEL),
        ),
    ]
