# Generated by Django 4.2.25 on 2026-02-09 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
