import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import api from '../api/axios';

export default function CourseCreate() {
  const navigate = useNavigate();
  
  const [subjects, setSubjects] = useState([]);
  const [formData, setFormData] = useState({
    subject: '',
    title: '',
    slug: '',
    course_code: '',
    overview: ''
  });
  
  // image handling states
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  // track if a file is currently hovering over the dropzone 
  const [isDragging, setIsDragging] = useState(false);
  // UI states
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  // fetch available subjects
  useEffect(() => {
    const fetchSubjects = async () => {
      try {
        const response = await api.get('courses/subjects/'); 
        const subjectsData = response.data.results ? response.data.results : response.data;
        const safeSubjects = Array.isArray(subjectsData) ? subjectsData : [];
        setSubjects(safeSubjects);

        // auto-selecct the first subject if available to prevent empty form submissions
        if (safeSubjects.length > 0) {
          setFormData(prev => ({ ...prev, subject: safeSubjects[0].id }));
        }
      } catch (err) {
        setError('Could not load subjects. Are you sure the API endpoint is correct?');
      } finally {
        setIsLoading(false);
      }
    };
    fetchSubjects();
  }, []);

  // auto generates a slug
  const handleTitleChange = (e) => {
    const newTitle = e.target.value;
    const autoGeneratedSlug = newTitle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-') 
      .replace(/(^-|-$)+/g, ''); 
    setFormData({ ...formData, title: newTitle, slug: autoGeneratedSlug });
  };

  // handle text input
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // handle normal click to upload
  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) processFile(file);
  };

  // Triggered when a file is dragged over the dropzone
  const handleDragOver = (e) => {
    e.preventDefault(); // prevent browser open the file in a new tab
    setIsDragging(true); 
  };

  // triggered when a file leaves the dropzone area without dropping
  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragging(false); 
  };

  // triggered when the user releases the mouse to drop the file
  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragging(false);
    
    const file = e.dataTransfer.files[0];
    if (file) processFile(file);
  };

  // file processing logic
  const processFile = (file) => {
    // type validation to ensure is images
    if (!file.type.startsWith('image/')) {
      alert('Please upload an image file (PNG, JPG, GIF).');
      return;
    }
    setImageFile(file);
    setImagePreview(URL.createObjectURL(file));
  }

  // handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setIsSubmitting(true);

    const submitData = new FormData();
    submitData.append('subject', formData.subject);
    submitData.append('title', formData.title);
    submitData.append('slug', formData.slug);
    submitData.append('course_code', formData.course_code);
    submitData.append('overview', formData.overview);
    
    if (imageFile) {
      submitData.append('image', imageFile);
    }

    try {
      await api.post('courses/teacher/mine/', submitData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      navigate('/dashboard');
    } catch (err) {
      if (err.response && err.response.data) {
        const errorData = err.response.data;
        const firstErrorKey = Object.keys(errorData)[0];
        setError(`${firstErrorKey}: ${errorData[firstErrorKey]}`);
      } else {
        setError('Failed to create course. Please try again.');
      }
      setIsSubmitting(false);
    }
  };

  if (isLoading) return <div className="min-h-screen flex items-center justify-center animate-pulse text-indigo-600">Loading...</div>;

  return (
    <div className="min-h-screen bg-slate-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <Link to="/dashboard" className="text-sm font-medium text-indigo-600 hover:text-indigo-500 flex items-center gap-1 mb-2">
            &larr; Back to Dashboard
          </Link>
          <h1 className="text-3xl font-extrabold text-slate-900">Create a New Course</h1>
        </div>

        {error && <div className="bg-red-50 p-4 mb-6 rounded-md text-red-700 text-sm">{error}</div>}

        <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
          <form onSubmit={handleSubmit} className="p-8 space-y-6">
            
            {/* photo upload*/}
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Course Cover Image</label>
              
              <div 
                onDragOver={handleDragOver}
                onDragLeave={handleDragLeave}
                onDrop={handleDrop}
                className={`mt-1 flex justify-center px-6 pt-5 pb-6 border-2 rounded-xl transition-all duration-200 group 
                  ${isDragging 
                    ? 'border-indigo-500 bg-indigo-50 scale-[1.02]'  // 拖拽时的激活样式
                    : 'border-slate-300 border-dashed bg-slate-50 hover:border-indigo-500' // 默认样式
                  }`}
              >
                <div className="space-y-1 text-center">
                  {imagePreview ? (
                    <div className="relative animate-fade-in">
                      <img src={imagePreview} alt="Preview" className="mx-auto h-48 w-auto rounded-lg object-cover shadow-sm" />
                      <button 
                        type="button" 
                        onClick={() => { setImageFile(null); setImagePreview(null); }}
                        className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 shadow hover:bg-red-600 cursor-pointer transition-transform hover:scale-110"
                      >
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
                      </button>
                    </div>
                  ) : (
                    <>
                      <svg className={`mx-auto h-12 w-12 transition-colors ${isDragging ? 'text-indigo-600' : 'text-slate-400 group-hover:text-indigo-500'}`} stroke="currentColor" fill="none" viewBox="0 0 48 48">
                        <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                      <div className="flex text-sm text-slate-600 justify-center">
                        <label className="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500 px-1">
                          <span>Upload a file</span>
                          <input name="image" type="file" accept="image/*" className="sr-only" onChange={handleImageChange} />
                        </label>
                        <p className="pl-1">or drag and drop</p>
                      </div>
                      <p className="text-xs text-slate-500">PNG, JPG, GIF up to 5MB</p>
                    </>
                  )}
                </div>
              </div>
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-1">Subject</label>
              <select name="subject" required value={formData.subject} onChange={handleChange} className="block w-full px-4 py-3 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500">
                {subjects.map(sub => <option key={sub.id} value={sub.id}>{sub.title}</option>)}
              </select>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div className="sm:col-span-2">
                <label className="block text-sm font-semibold text-slate-700 mb-1">Course Title</label>
                <input type="text" name="title" required value={formData.title} onChange={handleTitleChange} className="block w-full px-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500" />
              </div>
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">URL Slug</label>
                <input type="text" name="slug" readOnly value={formData.slug} className="block w-full px-4 py-3 border border-slate-300 bg-slate-100 text-slate-500 rounded-lg" />
              </div>
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Course Code</label>
                <input type="text" name="course_code" required value={formData.course_code} onChange={handleChange} className="block w-full px-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500" />
              </div>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-1">Course Overview</label>
              <textarea name="overview" required rows="4" value={formData.overview} onChange={handleChange} className="block w-full px-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 resize-y"></textarea>
            </div>

            <div className="pt-4 flex justify-end gap-4 mt-8">
              <Link to="/dashboard" className="px-6 py-2.5 text-sm font-semibold text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50">Cancel</Link>
              <button type="submit" disabled={isSubmitting || subjects.length === 0} className="px-6 py-2.5 text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg disabled:bg-indigo-400 cursor-pointer">
                {isSubmitting ? 'Creating...' : 'Create Course'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}